# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.hostname = "rails.paynedigital.com"

  # we assume we live in a directory like ~/code/vagrant
  # and all our ruby projects live in ~/code/ruby
  config.vm.synced_folder "../../ruby", "/home/vagrant/ruby"

  # rails testing
  config.vm.network :forwarded_port, guest: 3000, host: 3000

  # make sure everything's up to date first; makes our puppet
  # manifests a bit cleaner
  config.vm.provision :shell, :inline => "apt-get update -q"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "conf/puppet/manifests"
    puppet.module_path   = "../conf/puppet/modules"
  end

end
